### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by anjomro** [paeber/m5hamote#1]
Hey,
Your project looks super cool,  i'm glad that i'm not the only one wanting to program the M5Paper in Micropython. :)

For your project i would kindly ask you to consider adding a license. That would give a good base for contributions. To find the right license [choosealicense.com](https://choosealicense.com) might be a good resource.

Best Regards, Anton

**Comment by paeber** [comment]
Hi there,
Thanks a lot for your intrest. This motivates to continue the project. I try to do some progress here soon. I just added MIT license.
I hope the UIFlow library makes some progress as I would like to see SD card access (load configuration and icons from SD) and some power improvements like touch interrupt to wake the device from sleep. I saw some solutions in C but Micropython would be greate :)

Let me know if you achieved something.
Best Regards, Pascal
